name: weather_module
description: not a module
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # REST API
  dio: ^4.0.6
  retrofit: ^3.3.0

  # Internet connection
  cross_connectivity: ^3.0.5

  # UI
  material_design_icons_flutter: ^6.0.7096
  google_fonts: ^4.0.3
  animations: ^2.0.7

  # Utils
  path_provider: ^2.0.13
  url_launcher: ^6.0.20

  # State Management
  flutter_bloc: ^8.1.2

  # Architecture
  dartz: ^0.10.1
  kt_dart: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0

  # Local Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # Prompting
  flash: ^2.0.5+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  #Dart best practices
  flutter_lints: ^2.0.0

  # Testing
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

  #Auto-Code Generation
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  retrofit_generator: ^4.1.2
  json_serializable: ^6.5.4
  injectable_generator: ^1.5.3

  #Code Generator
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

